graph LR

    id1(Publishing engineering)
    id2(Information Architecture)
    id3(Content Strategy)
    id4(User Experience)
    
    id1 -.- id2
    id3 -.- id4

    style id1 fill:#fff,stroke:#000,stroke-width:4px
    style id2 fill:#fff,stroke:#000,stroke-width:4px
    style id3 fill:#fff,stroke:#000,stroke-width:4px
    style id4 fill:#fff,stroke:#000,stroke-width:4px
